import React from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import Image from "next/image";
import { Button } from "./ui/button";
import ProjectsData from "@/data/projects.json";
import Link from "next/link";
import Title from "@/components/ui/title";

export type Feature = {
  id: string;
  name: string;
  description: string;
};

export type Project = {
  id: string;
  title: string;
  description: string;
  repo_link: string;
  demo_link: string | null;
  download_link?: string;
  image: string;
  used_technologies: Array<UsedTechnology>;
  details_image: string;
  features: Feature[];
  intro: string;
  api_doc_link: null | string;
};
export type UsedTechnology = {
  id: string;
  name: string;
};

const Projects = () => {
  return (
    <div className="my-20">
      <Title title="Real-World Projects"></Title>
      <div className="my-4 text-2xl font-semibold">
        MyanCare (Telehealth App)
      </div>
      <div className="flex">
        <Image
          src={"/projects/teleconsult.jpg"}
          alt="project-image"
          width={900}
          height={300}
          className="my-2 rounded-t-md"
        ></Image>
        {/* <Image
          src={"/projects/myancare/voice-call-ui.png"}
          alt="project-image"
          width={400}
          height={800}
          className="my-2 rounded-t-md "
        ></Image>
        <Image
          src={"/projects/myancare/call-feedbacks.png"}
          alt="project-image"
          width={400}
          height={800}
          className="my-2 rounded-t-md "
        ></Image>{" "}
        <Image
          src={"/projects/myancare/call-feedback-ratings.png"}
          alt="project-image"
          width={400}
          height={800}
          className="my-2 rounded-t-md "
        ></Image>
        <Image
          src={"/projects/myancare/transaction-lists.png"}
          alt="project-image"
          width={400}
          height={800}
          className="my-2 rounded-t-md "
        ></Image>
        <Image
          src={"/projects/myancare/health-articles.png"}
          alt="project-image"
          width={400}
          height={800}
          className="my-2 rounded-t-md "
        ></Image>{" "}
        <Image
          src={"/projects/myancare/emergency-services.png"}
          alt="project-image"
          width={400}
          height={800}
          className="my-2 rounded-t-md "
        ></Image>{" "} */}
        {/* <Image
          src={"/projects/myancare/home-page.png"}
          alt="project-image"
          width={400}
          height={800}
          className="my-2 rounded-t-md "
        ></Image> */}
      </div>
      <div>
        <div className="text-lg">My Contributions to MyanCare Application</div>

        <div className="text-md my-4">
          ╰┈➤ Full-stack Development – Developed Admin Panel (frontend) and also
          built and optimized APIs for patient and doctor apps.
          <br />
          ╰┈➤ Feature Development – Developed Health Articles, Hospital Booking
          Form, Call-Feedback Ratings and Enhanced Authorization System.
          <br />
          ╰┈➤ Articles Management: – Built a module for managing
          healthcare-related articles, including creation, editing, and
          deletion. Implemented search and filtering options for easy
          navigation.
          <br />
          ╰┈➤ Call Feedback Records: – Developed a feature to track and display
          call feedback from patients and doctors. Enabled administrators to
          analyze feedback trends and improve service quality.
          <br />
          ╰┈➤ VoIP Migration – Migrated the VoIP feature to a new service after
          the previous one was deprecated.
          <br />
          ╰┈➤ Real-time & Webhooks – Managed call logs for appointment calls and
          handled real-time user events.
          <br />
          ╰┈➤ Performance Optimization – Improved wallet transaction queries for
          better efficiency.
          <br />
          ╰┈➤ Doctor Income Reports: – Created a reporting system to track and
          display income generated by doctors. Optimized database queries,
          reducing report generation time by 40%. This feature was helpful in a
          real-world scenario where doctors were paid or unpaid, and the
          reporting system helped to identify and manage the income.
          <br />
          ╰┈➤ Top 10 Doctors – Designed a feature to identify and display the
          top 10 doctors based on appointment volume.
          <br />
          ╰┈➤ Financial and User Reports: – Implemented Monthly Payment Methods
          Report to track payment trends. Optimized queries to handle large
          datasets and generate reports in real-time.
          <br />
          ╰┈➤ Code Refactoring – Rewrote parts of the legacy codebase to improve
          maintainability.
        </div>

        <div className="text-md my-4">
          <div className="rounded-md bg-secondary p-3">
            <div className="text-lg font-semibold">Impact .ᐟ</div>
            <p>
              Ensured uninterrupted service during VoIP migration. Delivered a
              more secure and efficient platform for patients and doctors.
              Improved admin panel performance, enabling real-time data analysis
              for over 10,000 users. Delivered actionable insights to
              administrators, enhancing decision-making and platform efficiency.
            </p>
          </div>
        </div>
      </div>

      <hr />

      <div className="my-4 text-2xl font-semibold">
        YinThway (Call Center Platform)
      </div>
      <div className="flex">
        <Image
          src={"/projects/myancare/yinthway-banner.webp"}
          alt="project-image"
          width={900}
          height={300}
          className="my-2 rounded-t-md"
        ></Image>
      </div>

      <div>
        <div className="text-lg">My Contributions to YinThway</div>

        <div className="text-md my-4">
          ╰┈➤ Full-stack Development – Developed Admin Panel (frontend) and also
          the (backend) APIs.
          <br />
          ╰┈➤ Baby Tracker – Developed a feature to track and monitor a baby’s
          growth and developmental milestones (e.g., weight, height,
          vaccinations, and feeding schedules). Designed an intuitive user
          interface for parents to input and view data. Implemented
          notifications and reminders for upcoming vaccinations or checkups.
          <br />
          ╰┈➤ Knowledge Sharing Development Milestones: – Created a
          knowledge-sharing module to provide parents with educational content
          about child development milestones. Organized content into categories
          (e.g., physical, cognitive, and emotional development) for easy
          navigation.Enabled healthcare providers to update and share new
          content through the admin panel.
        </div>
        <div className="text-md my-4">
          <div className="rounded-md bg-secondary p-3">
            <div className="text-lg font-semibold">Impact .ᐟ</div>
            <p>
              Enabled over 1,000 parents to track their baby’s growth and
              receive timely reminders for vaccinations. Increased user
              engagement on the platform by 25% through the knowledge-sharing
              module. Improved the quality of remote consultations by providing
              healthcare providers with easy access to baby records.
            </p>
          </div>
        </div>
      </div>
      <hr />
      <div className="my-4 text-2xl font-semibold">
        Sun Community Health (EMR Platform)
      </div>
      <div className="flex">
        <Image
          src={"/projects/myancare/sun.jpg"}
          alt="project-image"
          width={900}
          height={300}
          className="my-2 rounded-t-md"
        ></Image>
      </div>

      <div>
        <div className="text-lg">My Contributions to Sun Community Health</div>

        <div className="text-md my-4">
          ╰┈➤ Full-stack Development – Developed Admin Panel (frontend) and also
          the (backend) APIs.
          <br />
          ╰┈➤ EMR Edit Feature: – Developed a user-friendly form for doctors to
          edit patient EMRs. Enabled flexible editing, allowing doctors to
          update records dynamically without restrictions. Implemented
          validation and error handling to ensure data accuracy and consistency.
          Integrated the feature with the platform’s database, ensuring
          real-time updates and synchronization
          <br />
          ╰┈➤ Doctor register Feature: – Developed registering doctor feature
          through admin panel Enabled doctors to create and manage their
          profiles, editing information.
        </div>
        <div className="text-md my-4">
          <div className="rounded-md bg-secondary p-3">
            <div className="text-lg font-semibold">Impact .ᐟ</div>
            <p>
              Enabled over 500 doctors to create and edit EMRs efficiently,
              reducing data entry time by 30%. Improved data accuracy by 20%
              through form validation and error handling.
            </p>
          </div>
        </div>
      </div>

      <div className="my-10 h-[0.5px] w-full bg-black"></div>

      <Title title="My Creations"></Title>
      <div className="my-5 grid gap-8 md:grid-cols-2 lg:grid-cols-3">
        {ProjectsData.my_creations.map((project: Project) => (
          <div key={project.id} className="">
            <Card>
              <div className="m-0 p-0">
                <Image
                  src={project.image}
                  alt="project-image"
                  width={400}
                  height={400}
                  className="w-full rounded-t-md "
                ></Image>
              </div>

              <CardHeader>
                <CardTitle>{project.title}</CardTitle>
              </CardHeader>

              <CardContent>
                <CardDescription>{project.description}</CardDescription>
              </CardContent>

              <CardFooter>
                <Link href={`/projects/${project.id}`}>
                  <Button variant="retro" size="sm">
                    View Details
                  </Button>
                </Link>
              </CardFooter>
            </Card>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Projects;
